### ISSUE TITLE
프레임워크 도입에 대해서

### ISSUE THREAD

**Issue by dolfalf** [dobupower/QRR#1]
선언형프로그래밍에서 꽤 널리 사용되는 아키텍쳐, 상태관리, 그리고 UI구성에 필요한 아래 프레임 워크를 제안합니다.   
검토해 보시고 도입여부 결정해주세요.

- RiverPod 상태관리 
- MVVM 아키텍쳐
- Atomic Design기반 UI구성  -> 이건 프레임워크는 아님

## 참고링크
- [[Flutter の RiverpodライブラリでMVVMを実現させよう！](https://techblog.ldi.co.jp/entry/2023/12/04/104952)](https://techblog.ldi.co.jp/entry/2023/12/04/104952)
- [Flutter x Atomic Design で堅牢なデザインパターンを実現しよう](https://zenn.dev/nagakuta/articles/25c8aaf7744830bdab3d)

**Comment by dobupower** [comment]
넵 검토해보겠습니다.

**Comment by dev-baek** [comment]
좀더 공부하고 도입하도록 하겠습니다. 조언 감사합니다.

**Comment by dolfalf** [comment]
@dobupower 시간이 걸릴것 같으면 위에 프레임워크 생각하지 마시고 구현중심으로 작업하셔도 됩니다. 
나중에 레뷰 또는 리팩토링하면 되니까요.

**Comment by dev-baek** [comment]
네 지금 카카오클라우드에서 교육을 받고있어서 작업을 할 시간이 적어서요 최대한 빨리 작업 업데이트 하도록하겠습니다.

**Comment by wnstjd0333** [comment]
@dobupower 
상태관리에 대해서 Provider를 도입하셨네요.
비교적 작은 프로젝트라면 Provider도 괜찮지만

이번프로젝트에서 RiverPod을 사용해보는것은 어떨까요?
Riverpod는 상태가 위젯 트리와 분리되어 있기 때문에 유연하게 상태를 관리 할 수 있어요
학습에 시간이 많이 소요될 것 같으면 Provider도 OK입니다.

**Comment by dev-baek** [comment]
네 RiverPod로 구현해 보겠습니다.
