### ISSUE TITLE
owner 사용자의 Google 로그인 기능 사용에 대해

### ISSUE THREAD

**Issue by dev-baek** [dobupower/QRR#13]
![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-27 at 05 52 06](https://github.com/user-attachments/assets/a44244c0-c79d-4557-8020-33cab39ba5ef)
1안: 위 화면에서 체크박스가 체크된 사용자(owner)의 정보가 Firestore에 등록되어 있지 않을 시 점포 정보 및 사진 등의 정보를 입력받는 페이지 출력

2안: owner는 Google 로그인 기능 사용금지

<img width="300" alt="스크린샷 2024-09-27 오전 5 58 34" src="https://github.com/user-attachments/assets/d7da3c64-3880-4b21-8df0-cc3a3e5907ee">

notion에서는 관리자는 초대 코드나 특정 도메인으로 가입할 수 있다고 해서 저는 2안이 더 적합하다고 생각하는데 어떤 방식이 좋을까요?

**Comment by wnstjd0333** [comment]
@dobupower 
꼼꼼하게 봐주셔서 감사해요
2안으로 부탁드릴게요

**Comment by dev-baek** [comment]
넵 2안으로 진행하겠습니다.
