### ISSUE TITLE
유저 고유 숫자 코드에 관한 이슈

### ISSUE THREAD

**Issue by dev-baek** [dobupower/QRR#19]
<img width="214" alt="스크린샷 2024-10-15 오전 11 01 47" src="https://github.com/user-attachments/assets/d27510b2-95fb-4a78-af46-a2bf102861c2">

위 화면에서 유저의 고유 숫자 코드로 유저를 식별하여 거래를 진행하는 과정이 있습니다.
다만 어떤기준으로 유저에게 코드를 부여 하는가에 대해 여쭤보고 싶습니다.

제가 생각한 부여 기준
1. 가입한 순서 
2. 중복 검사 후 램덤으로 부여
3. 고유 숫자 코드가 아닌 이메일을 통한 유저 식별

**Comment by wnstjd0333** [comment]
기준에 대해서 생각해 보셨네요

> 2. 중복 검사 후 램덤으로 부여

로 해요

**Comment by dev-baek** [comment]
넵! 중복 검사 후 램덤으로 부여로 하겠습니다.
