### ISSUE TITLE
시스템 구성도 요약 1안 , 2안

### ISSUE THREAD

**Issue by donghyuk0605** [dobupower/QRR#2]
### 백민규 학생이 처음에 구성한 시스템 구성도(1안)

```mermaid
graph TD;
    Flutter_Client[Flutter 클라이언트] -->|요청/응답| Spring_Backend[Spring 백엔드 서버]
    
    subgraph Debian Linux  OS
        Spring_Backend[Spring 백엔드 서버-예시] -->|데이터 저장/조회| PostgreSQL[PostgreSQL 데이터베이스]
        Spring_Backend -->|인증| Auth_Service[일반 인증 서비스]
        Spring_Backend -->|파일 업로드/다운로드| Storage_Service[일반 스토리지 서비스]
    end
```

### 회의를 통해 변경한 현재 시스템 구성도(2안)
```mermaid
graph TD;
    Flutter_Client[Flutter 클라이언트] --> |데이터 저장/조회| Firestore[Firebase Firestore - 데이터베이스]
    Flutter_Client -->|인증| Auth[Firebase Authentication - 인증 서비스]
    Flutter_Client -->|파일 업로드/다운로드| Storage[Firebase Storage - 스토리지 서비스]
    
    subgraph Firebase
        Firestore[Firebase Firestore - 데이터베이스]
        Auth[Firebase Authentication - 인증 서비스] 
        Storage[Firebase Storage - 스토리지 서비스]
    end

```
```
개념 구분
Debian: 운영 체제(OS)로, 서버 환경에서 사용됨.
Firebase: 클라우드 서비스 플랫폼으로, 인증, 데이터 저장, 파일 스토리지 등을 제공.

```
**설명**

1. 초기 구성도 (Debian 서버 기반):
  - Flutter 클라이언트는 Spring(예시) 백엔드 서버와 통신.
  - Debian 서버 내에 Spring 백엔드 서버, PostgreSQL 데이터베이스, 인증 및 스토리지 서비스가 포함되어 있음.
2. 현재 변경된 구성도 (Firebase 기반):
  - Flutter 클라이언트는 Firebase 플랫폼과 통신.
  - Firebase 내에 Firestore 데이터베이스, Authentication, Storage 서비스가 포함되어 있음.

**Comment by dev-baek** [comment]
cloud_firestore와 Authentication를 이용해 회원가입을 구현했습니다.

**Comment by donghyuk0605** [comment]
> cloud_firestore와 Authentication를 이용해 회원가입을 구현했습니다.

@dobupower 
벌써 거기까지하신건가요?!
깃에 초대된 분들 그러면 파이어베이스 프로젝트에도 시간나실때 초대좀 부탁드릴께요!

**Comment by dev-baek** [comment]
넵

**Comment by samuelyyy** [comment]
제시하신, 2안에 대해, 어제 백민규와 같이 이야기 했습니다. HAB은 Backend에 대해 개발할 필요가 없다고 하지만, 내 생각에는 Backend가 필요합니다. 학생 스스로 실력 향상과, 동시에 개발된 결과물을 한국에서 충분히 테스트해야 합니다. 아무튼 위의 2안으로 진행합시다.

**Comment by donghyuk0605** [comment]
> 제시하신, 2안에 대해, 어제 백민규와 같이 이야기 했습니다. HAB은 Backend에 대해 개발할 필요가 없다고 하지만, 내 생각에는 Backend가 필요합니다. 학생 스스로 실력 향상과, 동시에 개발된 결과물을 한국에서 충분히 테스트해야 합니다. 아무튼 위의 2안으로 진행합시다.

2안에서 개발에 집중하고 개발이 빨리 완료된다면 2안으로 진행할수있어서 이부분 참고 부탁드립니다. 인프라를 만들고 개발은하는 것에서 개발을 하고 인프라를 한다

**Comment by donghyuk0605** [comment]
> 제시하신, 2안에 대해, 어제 백민규와 같이 이야기 했습니다. HAB은 Backend에 대해 개발할 필요가 없다고 하지만, 내 생각에는 Backend가 필요합니다. 학생 스스로 실력 향상과, 동시에 개발된 결과물을 한국에서 충분히 테스트해야 합니다. 아무튼 위의 2안으로 진행합시다.

네, 2안으로 진행하는 인식으로 알겠습니다.
그리고 2안에서 개발에 집중하고, 개발이 빨리 완료된다면 해당  1안으로 진행할 수 있습니다. 이 부분을 참고부탁드립니다!

**Comment by samuelyyy** [comment]
OK
