### ISSUE TITLE
UI깨짐 현상

### ISSUE THREAD

**Issue by wnstjd0333** [dobupower/QRR#5]
아래와 같이 앱을 기동하면 열리는 화면(First Screen)이 깨짐 현상이 있어요(Pixel 3a)

화면이 큰 단말기 기준으로 높이값을 고정값으로 지정한것이 원인이네요.
아래의 버그를 고쳐보실래요?
(hint: 고정값을 상대값으로 수정)

<img src="https://github.com/user-attachments/assets/556c776d-8e33-4fea-91ea-9b1630744c90" width="250"/>

**Comment by dev-baek** [comment]
넵 상대값으로 바꿔보겠습니다.
